export PATH="/opt/texlive/2023/bin/x86_64-linux/:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.nimble/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.config/emacs/bin:$PATH"
export PATH="$HOME/software/lutris-GE-Proton8-26-x86_64/bin/:$PATH"
export PATH="$HOME/software/jdtls/bin:$PATH"
export PATH="$HOME/software/haxe-4.2.5:$PATH"
export PATH="$HOME/software/zig-stable:$PATH"
export PATH="$HOME/software/Telegram:$PATH"
export PATH="$HOME/Games/openttd-jgrpp:$PATH"
export PATH="$HOME/Games/MultiMC:$PATH"
export PATH="$DENO_INSTALL/bin:$PATH"

. "$HOME/.cargo/env"
