#!/bin/bash

bspc monitor "eDP" -d 1 2 3 4 5
bspc monitor "HDMI-A-0" -d 6 7 8 9 10

bspc config border_width   2
bspc config window_gap     8
bspc config top_padding    10
bspc config right_padding  10
bspc config left_padding   10
bspc config bottom_padding 10

bspc config split_ratio        0.5
bspc config borderless_monocle false
bspc config gapless_monocle    false

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1  move
bspc config pointer_action2  resize_corner

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

xsetroot -cursor_name left_ptr

bspc rule -a Firefox desktop=^2

# pgrep eww > /dev/null || eww daemon &
# eww open bar &
polybar -r &
