-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- Prevent from using arrow keys. HJKL rules
-- vim.cmd[[nmap <silent> <Up> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[nmap <silent> <Down> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[nmap <silent> <Right> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[nmap <silent> <Left> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[imap <silent> <Up> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[imap <silent> <Down> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[imap <silent> <Right> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[imap <silent> <Left> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[vmap <silent> <Up> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[vmap <silent> <Down> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[vmap <silent> <Right> <cmd>echo 'FOOOOOOL'<CR>]]
-- vim.cmd[[vmap <silent> <Left> <cmd>echo 'FOOOOOOL'<CR>]]
